DjudgePortal/blueprints/challenges.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   challenges.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   18 Jul 2022

@brief  handling of different challenges

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


from flask import (
    Blueprint,
    redirect,
    render_template,
    url_for,
    current_app,
    request,
    flash,
)
from werkzeug.exceptions import abort
from collections import defaultdict

from sqlalchemy import func, select, text

from ..db import get_db
from ..auth import login_required
from .. import orms

from flask_login import current_user

import praw
import prawcore

from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    FormField,
    FieldList,
    BooleanField,
    Form,
    TextAreaField,
    SubmitField,
    SelectField,
    URLField,
)
from wtforms.validators import InputRequired, ValidationError, Optional, URL


bp = Blueprint("challenge", __name__)


@bp.route("/favicon.ico")
def favicon():
    return redirect(url_for("static", filename="favicon.ico"))


@bp.route("/index")
@bp.route("/")
def index():
    db_session = get_db()
    with db_session.begin():
        challenges = db_session.query(orms.ChallengeBase).all()

        return render_template("challenge/index.html", my_challenges=challenges)


def get_challenge(challenge_pk, db_session, orms):
    challenge = db_session.get(orms.ChallengeBase, challenge_pk)
    if challenge is None:
        abort(404, f"Challenge id {challenge_pk} does not exist")
    return challenge


@bp.route("/<int:id>/view")
def view(id):
    db_session = get_db()
    with db_session.begin():
        challenge = get_challenge(id, db_session, orms)
        undjudged = (
            db_session.query(orms.DjudgementInvitation)
            .filter_by(state=orms.DjudgementInvitation.States.Unacknowledged)
            .join(orms.SOTDAssociation)
            .filter_by(challenge_pk=challenge.pk)
            .order_by(orms.DjudgementInvitation.issued)
        )
        undjudged_dict = defaultdict(list)
        for invite in undjudged:
            undjudged_dict[invite.djudge].append(invite)
        return render_template(
            "challenge/view.html", challenge=challenge, undjudged=undjudged_dict
        )


class CategoryForm(Form):
    title = StringField("Title")
    guidance = TextAreaField("Guidance")


class CategoryEditForm(CategoryForm):
    category_type = SelectField(
        "Category Type",
        choices=[("numeric", "Numeric"), ("boolean", "Yes/no"), ("text", "Text")],
        render_kw={"readonly": True},
    )
    delete = SubmitField("Delete")


class CategoryCreateForm(CategoryForm):
    category_type = SelectField(
        "Category Type",
        choices=[("numeric", "Numeric"), ("boolean", "Yes/no"), ("text", "Text")],
    )
    submit = SubmitField("Add")
    cancel = SubmitField("Cancel")


def verify_reddit_user(form, field):
    print(f"I got field.data = {field.data}")
    return get_user(field.data)


def get_user(user_name):
    db_session = get_db()
    user = (
        db_session.query(orms.User)
        .filter_by(user_name_lower=user_name.lower())
        .one_or_none()
    )
    if user:
        return user

    reddit = praw.Reddit(current_app.config["REDDIT_CONFIG"], user_agent="DjudgePortal")
    print(f"user_name = '{user_name}'")
    praw_user = reddit.redditor(user_name)
    try:  # to make sure the user name exists
        _ = praw_user.id
    except prawcore.exceptions.NotFound as e:
        raise ValidationError(e)
    user = orms.User(user_name=praw_user.name)
    return user


class UserCreateForm(Form):
    user_name = StringField("User name", validators=[Optional(), verify_reddit_user])
    submit = SubmitField("Add")
    cancel = SubmitField("Cancel")


class UserShowForm(Form):
    user_name = StringField(
        "User name", validators=[InputRequired()], render_kw={"readonly": True}
    )
    delete = SubmitField("Delete")


def validate_dates(form, end_date_field):
    if end_date_field.data <= form.start_date.data:
        raise ValidationError(
            (
                f"The end date {end_date_field.data} needs to be later than the "
                f"start date {form.start_date.data}."
            )
        )
    return


class ChallengeForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired("A name is required")])
    title = StringField("Title", validators=[InputRequired("A name is required")])
    post_url = URLField("Post URL", validators=[URL()])
    search_string = StringField("Search string", validators=[InputRequired()])
    description = TextAreaField(
        "Description", validators=[InputRequired()], render_kw={"width": "90%"}
    )
    categories = FieldList(FormField(CategoryEditForm))
    add_category = FormField(CategoryCreateForm)
    owners = FieldList(FormField(UserShowForm))
    add_owner = FormField(UserCreateForm)
    djudges = FieldList(FormField(UserShowForm))
    add_djudge = FormField(UserCreateForm)
    is_active = BooleanField(
        (
            "Challenge is active (active challenges cannot be modified after "
            "participants have joined)"
        )
    )
    update = SubmitField("Update")
    cancel = SubmitField("Cancel")


class ChallengeGroupForm(FlaskForm):
    next_post_url = StringField("URL for next post")
    alert_djudges = BooleanField(
        "Djudges of this challenge group can receive reminder messages"
    )
    clear_url = SubmitField("Clear URL")
    update = SubmitField("Update")
    cancel = SubmitField("Cancel")


@bp.route("/group_view/<int:group_pk>", methods=("GET", "POST"))
@login_required
def group_view(group_pk):
    db_session = get_db()
    with db_session.begin():
        if not current_user.is_admin:
            abort(403, "You're not an admin")
        group = db_session.get(orms.ChallengeGroup, group_pk)
        if group is None:
            abort(404, "unknown group")

        form = ChallengeGroupForm(data=group)
        if form.validate_on_submit():
            if form.cancel.data:
                return redirect(url_for("user.view", pk=current_user.pk))

            if form.clear_url.data:
                group.next_post_url = None
                return redirect(url_for("user.view", pk=current_user.pk))
            group.next_post_url = form.next_post_url.data
            group.alert_djudges = form.alert_djudges.data
            return redirect(url_for("user.view", pk=current_user.pk))
        return render_template(
            "challenge/group_view.html",
            form=form,
            current_user=current_user,
            group=group,
        )


@bp.route("/djudge_ranking/<int:challenge_pk>")
@login_required
def djudge_ranking(challenge_pk):
    sort_column = request.args.get("sort_column")
    db_session = get_db()
    with db_session.begin():
        challenge = get_challenge(challenge_pk, db_session, orms)
        if not current_user.is_admin and current_user not in (
            challenge.owners + challenge.djudges
        ):
            abort(403, "You're not an admin, djudge, or owner")
        djudges = challenge.djudges
        nb_djudgements, nb_dqs = challenge.count_djudgements()
        djudge_points = challenge.compute_djudge_points()

        def row(djudge):
            n_tot = nb_djudgements[djudge]
            n_dqs = nb_dqs[djudge]
            points = djudge_points[djudge]
            return (djudge, n_dqs / n_tot * 100, points / n_tot)

        headings = ("#", "Djudge", "DQ rate", "per SOTD")
        if sort_column is None:
            sort_column_id = 1
        else:
            try:
                sort_column_id = headings[2:].index(sort_column) + 1
            except ValueError as err:
                message = f"Column '{sort_column}' does not exist."
                flash(message)
                raise err

        rows = [
            (i, *row)
            for (i, row) in enumerate(
                sorted(
                    (row(djudge) for djudge in djudges),
                    key=lambda row: -row[sort_column_id],
                ),
                start=1,
            )
        ]
        return render_template(
            "challenge/djudge_ranking.html",
            challenge=challenge,
            rows=rows,
            headings=headings,
            sort_column_id=sort_column_id,
        )


@bp.route("/brands_stats/<int:challenge_pk>")
@login_required
def brands_stats(challenge_pk):
    db_session = get_db()
    with db_session.begin():
        challenge = get_challenge(challenge_pk, db_session, orms)
        if not current_user.is_admin and current_user not in (
            challenge.owners + challenge.djudges
        ):
            abort(403, "You're not an admin, djudge, or owner")

        def sel(orm_type):
            return db_session.execute(
                select(
                    orm_type.brand,
                    func.count(orm_type.brand).label("count"),
                )
                .join(
                    orms.SOTDMetaDataAssociation,
                    orms.SOTDMetaDataAssociation.metadata_item_pk == orm_type.pk,
                )
                .join(
                    orms.SOTDAssociation,
                    orms.SOTDAssociation.pk
                    == orms.SOTDMetaDataAssociation.sotd_association_pk,
                )

DjudgePortal/blueprints/notes.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   notes.py

@author Dj Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   20 Jun 2023

@brief  blueprint for displaying note categories

Copyright © 2023 Dj Djundjila, TTS Rebuild Committee

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from flask import Blueprint, render_template
from werkzeug.exceptions import abort

from ..db import get_db
from .. import orms

from collections import defaultdict


bp = Blueprint("notes", __name__)


@bp.route("/notes/<int:note_category_pk>")
def view(note_category_pk):
    db_session = get_db()
    with db_session.begin():
        cat = db_session.get(orms.NoteCategory, note_category_pk)
        if cat is None:
            abort(404, "this Note Category does not exist")

        notes_list = cat.scores

        notes_dict = defaultdict(list)
        for note in sorted(
            notes_list,
            key=lambda note: note.djudgement.djudgement_invitation.sotd.created_utc,
        ):
            notes_dict[note.djudgement.djudgement_invitation.sotd.post].append(note)

        return render_template("notes/view.html", category=cat, notes_dict=notes_dict)

DjudgePortal/blueprints/sotds.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   sotds.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   16 Aug 2022

@brief  handling sotds

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from flask import (
    Blueprint,
    render_template,
)
from werkzeug.exceptions import abort

from ..db import get_db
from .. import orms


bp = Blueprint("sotd", __name__)


@bp.route("/sotd/<int:pk>")
def view(pk):
    db_session = get_db()
    with db_session.begin():
        sotd = db_session.get(orms.SOTD, pk)
        if not sotd:
            abort(404, "SOTD does not exist")
        return render_template("sotd/view.html", sotd=sotd)


@bp.route("/sotd/markdown/<int:sotd_pk>")
def view_markdown(sotd_pk):
    db_session = get_db()
    with db_session.begin():
        sotd = db_session.get(orms.SOTD, sotd_pk)
        if not sotd:
            abort(404, "SOTD does not exist")
        print(sotd.text)
        return render_template("sotd/view_markdown.html", sotd=sotd)


@bp.route("/sotd/<int:user_pk>/<int:challenge_pk>")
def view_sotds_for_user_in_challenge(user_pk, challenge_pk):
    db_session = get_db()
    with db_session.begin():
        user = db_session.get(orms.User, user_pk)
        if user is None:
            abort(404, "User does not exist")
        challenge = db_session.get(orms.ChallengeBase, challenge_pk)
        if challenge is None:
            abort(404, "Challenge does not exist")
        sotd_associations = sorted(
            db_session.query(orms.SOTDAssociation)
            .filter_by(challenge_pk=challenge_pk)
            .join(orms.SOTD, orms.SOTD.pk == orms.SOTDAssociation.sotd_pk)
            .filter_by(user_pk=user_pk),
            key=lambda assoc: assoc.sotd.created_utc,
        )

        return render_template(
            "sotd/view_sotds_for_user_in_challenge.html",
            user=user,
            challenge=challenge,
            sotd_associations=sotd_associations,
        )

DjudgePortal/templates/challenge/brand_stats.html
{% extends 'base.html' %}
{% from "macros.html" import format_user  with context %}
{% from "macros.html" import format_sotd  with context %}
{% from "macros.html" import format_challenge %}

{% block title %}Tallies for  {{ challenge.title }}{% endblock %}
{% block header %}
<h1>Brand usage stats for  {{ format_challenge(challenge) }}</h1>

{% endblock %}


{% block content %}
<article class="challenge">
  <h3> Overall usage </h3>
  {% for title, stats in brand_usage.items() %}
    <h4>{{ title }}</h4>
    <table class="table">
      <tr class="table__header">
        <th  class="table__cell"> #</th>
        <th  class="table__cell"> Brand</th>
        <th  class="table__cell"> Count</th>
      </tr>
      {% for brand, count in stats %}
        <tr class="table__row">
          <td class="table__cell">{{loop.counter}}</td>
          <td class="table__cell">{{ brand }}</td>
          <td class="table__cell">{{count}}</td>
        </tr>
      {% endfor %}
    </table>
  {% endfor %}
  </article>
{% endblock %}

DjudgePortal/templates/challenge/brand_stats_by_day.html
{% extends 'base.html' %}
{% from "macros.html" import format_user  with context %}
{% from "macros.html" import format_sotd  with context %}
{% from "macros.html" import format_challenge %}

{% block title %}Brand usage stats for {{ challenge.title }} by day{% endblock %}
{% block header %}
<h1 id="top">Brand usage stats for  {{ format_challenge(challenge) }} by day</h1>

{% endblock %}


{% block content %}
  <article class="challenge">
    {% for title, statsgroup in brand_usage.items() %}
      {% set category_loop = loop %}
      <h2 href="#cat_{{ category_loop.index }}">{{ title }}</h2>
      <ol>
        {% for post in statsgroup %}
          {% set post_loop = loop %}
          <li><a href="#day_{{ category_loop.index }}_{{ post_loop.index }}"> {{ post.title }}  <a href="#top">(back to top)</a></a>
        {% endfor %}
      </ol>
    {% endfor %}
    {% for title, statsgroup in brand_usage.items() %}
      {% set category_loop = loop %}
      <h2 id="cat_{{ category_loop.index }}">{{ title }}</h2>
      {% for post, stats in statsgroup.items() %}
        {% set post_loop = loop %}
        <h3 id="day_{{ category_loop.index }}_{{ post_loop.index }}"> {{ post.title }}  <a href="#top">(back to top)</a></h3>
        <div = class="flex-container">
          {% for frequency, brands in stats.items() %}
            <div>
              <h4> {{ frequency }} Use{% if frequency > 1 %}s{%endif%}:</h4>
              <ol>
                {% for brand in brands %}
                  <li>{{ brand  }}</li>
                {% endfor %}
              </ol>
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    {% endfor %}
  </article>
{% endblock %}

DjudgePortal/templates/challenge/create.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block header %}
  <h1>{% block title %}New Challenge{% endblock %}</h1>
{% endblock %}

{% block content %}
  <article class="challenge">
    <header>

    </header>
    <p class="body">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ wtf.quick_form(form) }}
        {{ form.csrf_token() }}


    </p>
  </article>
{% endblock %}

DjudgePortal/templates/challenge/delete.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block header %}
  <h1>{% block title %}Delete  Challenge {{challenge['name']}} {% endblock %}</h1>
{% endblock %}

{% block content %}
  <article class="challenge">
    <header>

    </header>
    <p class="body">
      Are you sure you want to delete the challenge '{{ challenge['name'] }}'? this cannot be undone.
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ wtf.quick_form(form) }}
        {{ form.csrf_token() }}


    </p>
  </article>
{% endblock %}

DjudgePortal/templates/challenge/djudge_ranking.html
{% extends 'base.html' %}
{% from "macros.html" import format_user  with context %}
{% from "macros.html" import format_sotd  with context %}
{% from "macros.html" import format_challenge %}

{% block title %}Tallies for  {{ challenge.title }}{% endblock %}
{% block header %}
<h1>Djudge Rankings  {{ format_challenge(challenge) }}</h1>

{% endblock %}


{% block content %}
<article class="challenge">
  <table style='font-size:80%' class="table">
    <tr class="table__header">
      {% for header in headings %}
      <th class="table__cell"><a href="{{ url_for('challenge.djudge_ranking', challenge_pk=challenge.pk, sort_column=header) }}">{{ header }}</a></th>
      {% endfor %}

    </tr>
    {% for row in rows %}
    <tr class="table__row">
      <td class="table__cell">
        {{ row[0] }} 
      </td class="table__cell">
      <td class="table__cell">
        {{ format_user(row[1]) }} 
      </td class="table__cell">
      <td class="table__cell">
        {{ "%.2f"|format(row[2]) }}%
      </td>
      <td class="table__cell">
        {{ "%.2f"|format(row[3]) }}
      </td>
    </tr>
    {% endfor %}
  </table>

  </article>
{% endblock %}

DjudgePortal/templates/challenge/edit.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block header %}
  <h1>{% block title %}Challenge {{challenge['name']}}{% endblock %}</h1>
{% endblock %}

{% block content %}
  <article class="challenge">
    <header>
      <div>
        <div class="about"> by {% for owner in challenge['owners'] %}u/{{ owner['user_name'] }}{% if not loop.last %}, {% endif %}{% endfor %}
      </div>
      {% if current_user.user_name in challenge.owners %}
        <a class="action" href="{{ url_for('challenge.update', pk=post['pk']) }}">Edit</a>
      {% endif %}
    </header>
    <div>
        {{ form.hidden_tag() }}
        {{ wtf.quick_form(form, form_type="horizontal", horizontal_columns=('xs', 2, 8)) }}
        {{ form.csrf_token() }}


    </div>
  </article>
{% endblock %}

DjudgePortal/templates/challenge/group_view.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html' %}
{% from "macros.html" import format_challenge %}

{% block title %} Challenge Group '{{ group.name }}' {% endblock %}
{% block header %}
  <h1></h1>
{% endblock %}

{% block content %}
  <article class="post">
    <header>
      <div> Your are {{ "%.2f"|format(current_user.percentage_djudged) }}% done and have {{ current_user.docket|length }} djudgements left to do. </div>
    </header>

    <h3>Contains challenges </h3>
    <div>
      <ol>
        {% for challenge in group.challenges %}
          <li> {{ format_challenge(challenge) }}</li>
        {% endfor %}
      </ol>
    </div>
    <form class="form form-horizontal" method="post" role="form">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}

      {{ wtf.form_field(form.next_post_url) }}
      {{ wtf.form_field(form.alert_djudges) }}
      {{ wtf.form_field(form.clear_url) }}
      {{ wtf.form_field(form.update) }}
      {{ wtf.form_field(form.cancel) }}
      {{ form.csrf_token() }}
    </form>
  </article>
{% endblock %}

DjudgePortal/templates/challenge/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Challenges{% endblock %}</h1>
{% endblock %}
{% block content %}
  {% for challenge in my_challenges %}
    <article class="post">
      <header>
        <div>
          <h1><a class="action" href="{{ url_for('challenge.view', id=challenge['pk']) }}">{{ challenge['name'] }}</a></h1>
          <div class="about"> by {% for owner in challenge['owners'] %}u/{{ owner['user_name'] }}{% if not loop.last %}
                   , 
          {% endif %}
             {% endfor %}</div>
        </div>
      </header>
      <p class="body">{{ challenge['title'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

DjudgePortal/templates/challenge/view.html
{% extends 'base.html' %}
{% from "macros.html" import format_user %}
{% from "macros.html" import format_post %}
{% from "macros.html" import format_challenge %}

{% block header %}
  <h1>{% block title %}Challenge '{{ challenge['title'] }}'{% endblock %}</h1>
{% endblock %}

{% block content %}
  <article class="challenge">
    <header>
      <h2> Short Name: {{ challenge.name }} </h2>
      {% if challenge.start_date %}
        <p> Running from {{ challenge.start_date }} until {{ challenge.end_date }}.</p>
      {% endif %}
      {% if challenge.currently_active() %}
        <p> This challenge is active and collecting participants.</p>
      {% else %}
        <p> This challenge is in draft state.</p>
      {% endif %}
      <div>
        <div class="about"> by {% for owner in challenge['owners'] %}{{ format_user(owner) }}{% if not loop.last %}, {% endif %}{% endfor %}</div>
      </div>
      <a href="{{ challenge.post_url }}" target="_blank">Original post</a>
    </header>
    <div style="padding: 10px; border: 2px solid black;">{{ challenge.description_markdown|safe }} </div>
    {% if challenge.current_post %}
    <div>
      <h3>Current Post:</h3>
      <a href="https://reddit.com{{ challenge.current_post.permalink }}" target="_blank"> {{ challenge.current_post.title }} </a>
    </div>
    {% endif %}
    <div>
      <h3> Categories Djudged: </h3>
      {% for title, category in challenge['categories'].items() %}
        <p><h4>{{ category }}</h4>
          {{ category.guidance_markdown|safe }}</p>
        {% endfor %}
    </div>
    <hr>


    {% if challenge.scavenger_hunts|length > 0 %}
      <div>
        <h3> Scavenger Hunts: </h3>
        {% for hunt in challenge.razor_scavenger_hunts %}
          <p><h4> Razor Scavenger Hunt {{ loop.index }}:</h4>
          <p>{{ hunt.weight }} points per hashtag, with a maximum of {{ hunt.max_score }} points.</p>
          <ol>
            {% for tag in hunt.tags %}

              <li> {{ tag.tag }} </li>
            {% endfor %}
          </ol>
        {% endfor %}
        {% for hunt in challenge.brush_scavenger_hunts %}
          <p><h4> Brush Scavenger Hunt {{ loop.index }}:</h4>
          <p>{{ hunt.weight }} points per hashtag, with a maximum of {{ hunt.max_score }} points.</p>
          <ol>
            {% for tag in hunt.tags %}

              <li> {{ tag.tag }} </li>
            {% endfor %}
          </ol>
        {% endfor %}
      </div>
      <hr>
    {% endif %}

    {% if challenge.sponsor_points|length > 0 %}
      <div>
        {% for sponsor_points in challenge.sponsor_points %}
          <p><h4> {{ sponsor_points.title }}:</h4>
          <p>{{ sponsor_points.weight }} points per sponsor, with a maximum of {{ sponsor_points.max_score }} points. {% if sponsor_points.property_name %} Only counted for SOTDs with property '{{ sponsor_points.property_name }}'.{% endif %}</p>
          <ol>
            {% for sponsor in sponsor_points.sponsors %}

              <li> {{ sponsor.name }} </li>
            {% endfor %}
          </ol>
        {% endfor %}
      </div>
      <hr>
    {% endif %}

    {% if challenge.analyses|length > 0 %}
      <h3> Rankings: </h3>
      <ol>
        {% for analysis in challenge.analyses %}
          {% if current_user.is_admin or current_user in challenge.djudges or current_user in challenge.owners %}
            <li>  <a href="{{ url_for('analysis.view', analysis_pk=analysis.pk, challenge_pk=challenge.pk) }}">{{ analysis.analysis_type }} </a> </li>
          {% else %}
            <li>  <a href="{{ url_for('analysis.public_view', analysis_pk=analysis.pk, challenge_pk=challenge.pk) }}">{{ analysis.analysis_type }} </a> </li>
          {% endif %}
        {% endfor %}
      </ol>
    {% endif %}

    {% if current_user.is_admin or current_user in challenge.djudges or current_user in challenge.owners %}
      {% if challenge.sotd_points_tallies|length > 0 %}
        <h3> Tallies: </h3>
    <p><a href="{{ url_for('tallies.tallies', challenge_pk=challenge.pk) }}"> Current tally of points </a></p>

    <p><a href="{{ url_for('challenge.djudge_ranking', challenge_pk=challenge.pk) }}"> Current ranking of djudges </a></p>
    <p><a href="{{ url_for('challenge.brands_stats', challenge_pk=challenge.pk) }}"> Brand usage </a></p>
    <p><a href="{{ url_for('challenge.brands_stats_by_day', challenge_pk=challenge.pk) }}"> Brand usage_by_day </a></p>
        <hr>
      {% endif %}
    {% endif %}
    {% if challenge.notes %}
      <h3> Notes: </h3>
      The following note categories have been applied to posts;
      <ol>
        {% for property_name, value in challenge.notes.items() %}
          <li> <a href="{{url_for('notes.view', note_category_pk=value[0].category_pk) }}">{{ value[0].title }}</a> </li>
        {% endfor%}
      </ol>
      <hr>
    {% endif %}
    {% if challenge.selection_tallies %}
      <h3> Selections: </h3>
      The following selections have been reviewed
      <ol>
        {% for title, template in challenge.selection_templates.items() %}
          {% if template.selected_sotd_associations() %}
            <li> <a href="{{url_for('djudgement.selection_view', template_pk=template.pk) }}">{{ title }}</a> </li>
          {% endif %}
        {% endfor%}
      </ol>
      <hr>
    {% endif %}


    <h3>Participants</h3>
    <ol>
      {% for participant in challenge['participants'] %}
        <li><a href="{{ url_for('sotd.view_sotds_for_user_in_challenge', user_pk=participant.pk, challenge_pk=challenge.pk) }}">Submissions</a> by {{ format_user(participant) }}
        </li>
      {% endfor %}
    </ol>
</div>
<div>
  <h3>Djudges</h3>
  <ol>
    {% for djudge in challenge['djudges'] %}
      <li>{{ format_user(djudge) }}</li>
    {% endfor %}
  </ol>
</div>
<div>
  <h3>Posts</h3>

  There are a total of {{ challenge.sotds|length }} SOTDs, or an average of {{ "%.2f"|format((challenge.sotds|length)/([1, challenge.posts|length]|max)) }} SOTDs per day.
  <ol>
    {% for post in challenge['posts'] %}
      <li>{{ format_post(post, challenge) }}</li>
    {% endfor %}
  </ol>
</div>
{% if current_user in challenge.djudges  and undjudged %}
  <div>
    <h3>Undjudged SOTDs</h3>
    {% for djudge, docket in undjudged.items() %}
      <h4> On the Hon. {{ format_user(djudge) }}'s docket</h4>
      <ol>
        {% for invitation in docket %}
          <li><a href="{{ url_for('sotd.view', pk=invitation.sotd.pk) }}"> Day {{ invitation.sotd.post.day_associations[invitation.challenge].day }}<a> of {{ format_challenge(invitation.challenge) }} by u/{{ invitation.sotd.author.user_name }} </li>
        {% endfor %}
      </ol>
    {% endfor %}
  </div>
{% endif %}
</article>
{% endblock %}