DjudgePortal/auth.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   auth.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   09 Jul 2022

@brief  handles login using reddit messages for authentication

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
    current_app,
)

from DjudgePortal import orms
from DjudgePortal.db import get_db

from datetime import datetime

import logging

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, BooleanField
from wtforms.validators import InputRequired, ValidationError

from flask_login import login_user, login_required, logout_user

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=("GET", "POST"))
def login():
    db_session = get_db()
    with db_session.begin():
        user_names = {t[0] for t in db_session.query(orms.User.user_name_lower)}

        def validate_token(form, field):
            user = (
                db_session.query(orms.User)
                .filter_by(user_name=form.user_name.data)
                .one_or_none()
            )
            if user is None:
                raise ValidationError(f"User '{form.user_name.data}' does not exist.")
            elif user.access_code is None:
                raise ValidationError(
                    "You haven't requested an access code for user "
                    f"'u/{user.user_name}' yet. Please follow the link to do "
                    "so."
                )
            elif user.access_code_valid_until < datetime.now().timestamp():
                raise ValidationError(
                    f"User u/{user.user_name}'s access code has expired, "
                    "please request a new one."
                )
            elif field.data != user.access_code:
                raise ValidationError("Incorrect access code.")

        def validate_user_name(form, field):
            if field.data.lower() not in user_names:
                raise ValidationError(
                    f"It seems user u/{field.data} is not an organiser of, "
                    "nor djudge or participant in any of the challenges I run"
                )

        class LoginForm(FlaskForm):
            user_name = StringField(
                "Reddit user name", validators=[InputRequired(), validate_user_name]
            )
            access_token = IntegerField(
                "Access token", validators=[InputRequired(), validate_token]
            )
            remember_me = BooleanField("Remember me", default=True)
            submit = SubmitField("Submit")
            cancel = SubmitField("Cancel")

        form = LoginForm()
        if form.errors:
            flash(form.errors)
            print(form.errors)
        if request.method == "POST":
            print("got POST request")
            print("form validated?", form.validate())
            print(form.errors)
            print(form)
        if form.validate_on_submit():
            if form.cancel.data:
                return redirect(url_for("challenge.index"))
            user = (
                db_session.query(orms.User)
                .filter_by(user_name=form.user_name.data)
                .one_or_none()
            )
            login_user(user, remember=form.remember_me.data)
            flash("Logged in successfully.")
            return redirect(url_for("challenge.index"))

    to_name = current_app.config["REDDIT_IDENTITY_BOT"]
    return render_template(
        "auth/login.html",
        form=form,
        to_name=to_name,
        message_url=(
            f"https://www.reddit.com/message/compose/?to={to_name}&subject="
            "Access%20Code&message=Pretty%20please!"
        ),
    )


@bp.route("/login_legacy", methods=("GET", "POST"))
def login_legacy():
    if request.method == "POST":
        logging.debug("logging in")
        user_name = request.form["user_name"].strip()
        access_code = request.form["access_code"]
        logging.info(
            f"log in attempt for user_name '{user_name}' with "
            f"access_code '{access_code}'"
        )
        db, orms = get_db()
        error = None

        def int_or_none(rep_string):
            try:
                return int(rep_string)
            except ValueError:
                return "FALSE"

        logging.debug("trying to start transaction to query user")
        with db.session.begin():
            logging.debug("started transaction")
            user = (
                db.session.query(orms.User)
                .filter_by(user_name_lower=user_name.lower())
                .one_or_none()
            )
            if user is None:
                error = f"User '{user_name}' is not registered."
            elif user.access_code is None:
                error = (
                    "You haven't requested an access code for user "
                    f"'{user_name}' yet. Please follow the link to do "
                    "so."
                )
            elif user.access_code_valid_until < datetime.now().timestamp():
                error = (
                    f"User {user_name}'s access code has expired, "
                    "please request a new one."
                )
            elif int_or_none(access_code) != user.access_code:
                print(
                    f"access_code ({access_code}) != user.access_code "
                    f"({user.access_code})"
                )
                error = "Incorrect access code."

            if error is None:
                logging.info(f"successfully logged in user '{user_name}'")
                session.clear()
                session["user_pk"] = user.pk
                return redirect(url_for("challenge.index"))
            logging.debug("ended transaction")
        logging.error(f"failed login with error '{error}'")
        flash(error)

    to_name = current_app.config["REDDIT_IDENTITY_BOT"]
    return render_template(
        "auth/login_legacy.html",
        message_url=(
            f"https://www.reddit.com/message/compose/?to={to_name}&subject="
            "Access%20Code&message=Pretty%20please!"
        ),
    )


# @bp.before_app_request
# def load_logged_in_user():
#     user_pk = session.get('user_pk')

#     if user_pk is None:
#         g.user = None
#     else:
#         db, orms = get_db()
#         g.user_pk = user_pk
#         logging.debug("trying to start transaction in load_logged_in_user")
#         with db.session.begin():
#             logging.debug("started transaction")
#             g.user = db.session.query(orms.User).filter_by(
#                 pk=user_pk).one_or_none()
#             logging.debug("ended transaction")


# def login_required(view):
#     @functools.wraps(view)
#     def wrapped_view(**kwargs):
#         if g.user is None:
#             return redirect(url_for('auth.login'))

#         return view(**kwargs)

#     return wrapped_view


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("challenge.index"))

DjudgePortal/blueprints/posts.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   posts.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   16 Aug 2022

@brief  handling posto for a given challeng

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from flask import (
    Blueprint,
    render_template,
)
from werkzeug.exceptions import abort
from .. import orms

from ..db import get_db

bp = Blueprint("post", __name__)


@bp.route("/post/<int:post_pk>/<int:challenge_pk>")
def view(post_pk, challenge_pk):
    db_session = get_db()
    with db_session.begin():
        post = db_session.get(orms.Post, post_pk)
        if not post:
            abort(404, "Post does not exist")
        challenge = db_session.get(orms.ChallengeBase, challenge_pk)
        if not challenge:
            abort(404, "Challenge does not exist")

        sotd_associations = (
            db_session.query(orms.SOTDAssociation)
            .filter_by(challenge_pk=challenge_pk)
            .join(orms.SOTD, orms.SOTD.pk == orms.SOTDAssociation.sotd_pk)
            .filter_by(post_pk=post.pk)
            .order_by(orms.SOTD.created_utc)
            .all()
        )

        return render_template(
            "post/view.html",
            post=post,
            challenge=challenge,
            sotd_associations=sotd_associations,
        )

DjudgePortal/blueprints/sotds.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   sotds.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   16 Aug 2022

@brief  handling sotds

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from flask import (
    Blueprint,
    render_template,
)
from werkzeug.exceptions import abort

from ..db import get_db
from .. import orms


bp = Blueprint("sotd", __name__)


@bp.route("/sotd/<int:pk>")
def view(pk):
    db_session = get_db()
    with db_session.begin():
        sotd = db_session.get(orms.SOTD, pk)
        if not sotd:
            abort(404, "SOTD does not exist")
        return render_template("sotd/view.html", sotd=sotd)


@bp.route("/sotd/markdown/<int:sotd_pk>")
def view_markdown(sotd_pk):
    db_session = get_db()
    with db_session.begin():
        sotd = db_session.get(orms.SOTD, sotd_pk)
        if not sotd:
            abort(404, "SOTD does not exist")
        print(sotd.text)
        return render_template("sotd/view_markdown.html", sotd=sotd)


@bp.route("/sotd/<int:user_pk>/<int:challenge_pk>")
def view_sotds_for_user_in_challenge(user_pk, challenge_pk):
    db_session = get_db()
    with db_session.begin():
        user = db_session.get(orms.User, user_pk)
        if user is None:
            abort(404, "User does not exist")
        challenge = db_session.get(orms.ChallengeBase, challenge_pk)
        if challenge is None:
            abort(404, "Challenge does not exist")
        sotd_associations = sorted(
            db_session.query(orms.SOTDAssociation)
            .filter_by(challenge_pk=challenge_pk)
            .join(orms.SOTD, orms.SOTD.pk == orms.SOTDAssociation.sotd_pk)
            .filter_by(user_pk=user_pk),
            key=lambda assoc: assoc.sotd.created_utc,
        )

        return render_template(
            "sotd/view_sotds_for_user_in_challenge.html",
            user=user,
            challenge=challenge,
            sotd_associations=sotd_associations,
        )

DjudgePortal/blueprints/users.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
@file   users.py

@author Djundjila <djundjila.gitlab@cloudmail.altermail.ch>

@date   16 Aug 2022

@brief  handling of users

Copyright © 2022 Djundjila

DjudgePortal is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DjudgePortal is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    url_for,
)
from werkzeug.exceptions import abort

from ..db import get_db
from .. import orms


bp = Blueprint("user", __name__)


@bp.route("/user/index")
def index():
    db_session = get_db()
    with db_session.begin():
        users = db_session.query(orms.User).filter_by(is_admin=False).all()

        return render_template("user/index.html", users=users)


@bp.route("/user/<string:username>/")
def view_by_name(username):
    db_session = get_db()
    with db_session.begin():
        user = (
            db_session.query(orms.User)
            .filter_by(user_name_lower=username.lower())
            .one_or_none()
        )
        if user is None:
            abort(404, f"User '{username}' is not known")

        groups = db_session.query(orms.ChallengeGroup).all()
        return render_template("user/view.html", user=user, groups=groups)


@bp.route("/user/<int:pk>")
def view(pk):
    db_session = get_db()
    with db_session.begin():
        user = db_session.get(orms.User, pk)
        if not user:
            flash("User does not exist", "error")
        return redirect(url_for("user.view_by_name", username=user.user_name))


# @bp.route('/user/<int:user_pk>/<int:challenge_pk>')
# def view_per_challenge(user_pk, challenge_pk):
#     db_session = get_db()
#     with db_session.begin():
#         user = db_session.get(orms.User, user_pk)
#         if not user:
#             flash("User does not exist", "error")
#         challenge = db_session.get(orms.Challenge, challenge_pk)
#         if not challenge:
#             flash("Challenge does not exist", "error")
#         return render_template('user/view_per_challenge.html', user=user)
#

DjudgePortal/templates/base.html
{% from "macros.html" import format_user %}
<!doctype html>
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>{% block title %}{% endblock %} - Djudge Portal</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style2.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<nav>
  <h1><a href="{{ url_for('challenge.index') }}">Djudge Portal</a></h1>
  <ul>
    {% if current_user.is_authenticated %}
      <li><span>{% if current_user.docket %} You have open<a  style="display: inline;"  href="{{ url_for('djudgement.index', djudge_pk=current_user.pk) }}">djudgements!</a>{% endif %}&nbsp; logged in as {% if current_user.is_admin %}administrator{% else %}user{% endif %} {{ format_user(current_user) }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>

<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

DjudgePortal/templates/macros.html
{% macro format_user(user) %}<a style="display: inline;" href="{{ url_for('user.view', pk=user.pk) }}">u/{{ user.user_name }}</a>{% endmacro%}

{% macro format_challenge(challenge) %}<a style="display: inline;" href="{{ url_for('challenge.view', id=challenge.pk) }}">{{ challenge.name }}</a>{% endmacro%}

{% macro format_note(note, mention_tag=False) %}
  {% if mention_tag %}
    <strong>{{ note.category.title }}:</strong>
  {% endif %}
  {% if current_user in note.category.challenge.djudges  or current_user in note.category.challenge.owners %}
    The Hon. Djudge {{ format_user(note.djudgement.djudgement_invitation.djudge) }}
  {% else %}
    An Anonymous Djudge
  {% endif %}
  remarked:
  <div style="padding: 10px; border: 2px solid black;">{{ note.note_markdown|safe }} </div>
{% endmacro %}

{% macro format_sotd(sotd) %}
  {{ format_user(sotd.author) }} <a style="display: inline;" href="{{ url_for('sotd.view', pk=sotd.pk) }}">posted</a>&nbsp;on {{ sotd.pst_datetime }} (Pacific Standard Time). <a href="https://reddit.com{{ sotd.permalink }}" target="_blank">Reddit Comment</a> (<a style="display: inline;" href="{{ url_for('sotd.view_markdown', sotd_pk=sotd.pk) }}">See markdown</a>)    <div style="padding: 10px; border: 2px solid black;">{{ sotd['markdown_text']|safe }} </div>
  {% if sotd['meta_info'] %}
    <p><strong>Detected Items:</strong><ul>
        {% for meta_info in sotd['meta_info'] %}
          <li> {{ meta_info['item']['html']|safe }}{% if meta_info.djudicial_dq %} (DQed){% endif %}
            {% if meta_info['hashtags'] %}
              [{% for hashtag_assoc in meta_info['hashtag_associations'] %}{{ hashtag_assoc.hashtag['tag'] }}{% if hashtag_assoc.djudicial_dq %} (DQed){% endif %}{{ ", " if not loop.last else "" }}
            {% endfor %}]
          {% endif %}
          </li>
        {% endfor %}
    </ul></p>
  {% endif %}
  {% if sotd.challenges %}
    This SOTD is part of the challenge{% if sotd.challenges|length > 133 %}s{% endif %}
    <ol>
      {% for challenge in sotd.challenges %}
        <li>{{ format_challenge(challenge) }}
        </li>
      {% endfor %}
    </ol>
    {% if current_user.is_authenticated %}
      {% if sotd in current_user.sotds_on_docket %}
        <p> You still need to <a style="display: inline;" href="{{ url_for('djudgement.adjudicate', invitation_pk=current_user.sotd_to_invite[sotd.pk]) }}">addjudicate this SOTD.</a></p>
      {% endif %}
      {% if sotd in current_user.sotds_addjudicated %}
        <p> You <a style="display: inline;" href="{{ url_for('djudgement.edit', djudgement_pk=current_user.sotd_to_djudgement[sotd.pk]) }}"> have addjudicated </a>this SOTD.</p>
      {% endif %}
    {% endif %}
  {% endif %}
  {% for inv in sotd.djudgement_invitations %}
    {% if current_user in inv.challenge.djudges or current_user in inv.challenge.owners %}
      <p>
        {% if inv.djudgement %}
          This SOTD was djudged by {{ format_user(inv.djudge) }} for {{ format_challenge(inv.challenge) }}
        {% else %}
          This SOTD is on {{ format_user(inv.djudge) }}'s docket for {{ format_challenge(inv.challenge) }}
        {% endif %}
        {% if current_user == inv.sotd_association.djudge and inv.challenge.has_meta_data_check %}
          <p><a style="display: inline;" href="{{ url_for('meta_data.validate', sotd_association_pk=inv.sotd_association.pk) }}"> Edit meta data </a></p>
        {% endif %}
      </p>
    {% endif %}

{% endfor %}
{% endmacro%}

{% macro format_sotd_association(sotd_association, show_notes=False) %}{{ format_user(sotd_association.sotd.author) }} <a style="display: inline;" href="{{ url_for('sotd.view', pk=sotd_association.sotd_pk) }}">posted</a>&nbsp;on {{ sotd_association.sotd.pst_datetime }} (Pacific Standard Time). <a href="https://reddit.com{{ sotd_association.sotd.permalink }}" target="_blank">Reddit Comment</a> (<a style="display: inline;" href="{{ url_for('sotd.view_markdown', sotd_pk=sotd_association.sotd_pk) }}">See markdown</a>)
  <div style="padding: 10px; border: 2px solid black;">{{ sotd_association.sotd['markdown_text']|safe }} </div>
  {% if current_user in sotd_association.challenge.djudges or current_user in sotd_association.challenge.owners %}
    {% if sotd_association.djudgement.disqualified %}
      <p> Djudged <strong>DISQUALIFIED ❌</strong></p>
    {% elif sotd_association.property_value("on theme").value == True %}
      <p> Djudged <strong>on theme ☑</strong></p>
    {% elif sotd_association.property_value("on theme").value == False %}
      <p>Djudged <strong>NOT on theme! ❌</strong></p>
    {% endif %}
  {% endif %}

  {% if sotd_association['meta_info'] %}
    <p><strong>Detected Items:</strong><ul>
        {% for meta_info in sotd_association['meta_info'] %}
          <li> {{ meta_info['item']['html']|safe }}{% if meta_info.djudicial_dq %} (DQed){% endif %}
            {% if meta_info['hashtags'] %}
              [{% for hashtag_assoc in meta_info['hashtag_associations'] %}{{ hashtag_assoc.hashtag['tag'] }}{% if hashtag_assoc.djudicial_dq %} (DQed){% endif %}{{ ", " if not loop.last else "" }}
            {% endfor %}]
          {% endif %}
          </li>
        {% endfor %}
      </ul>
    </p>
    {% if sotd_association.sponsor_uses %}
      <p>
        <strong>Sponsor Uses</strong>
        <ul>
          {% for use in sotd_association.sponsor_uses.values() %}
            <li>
              {{ use.sponsor }} ({{ use.sponsor_points.title }})
            </li>
          {% endfor %}
        </ul>
      </p>
    {% endif %}
  {% endif %}
  {% if current_user.is_authenticated %}
    {% if sotd_association.sotd in current_user.sotds_on_docket %}
      <p> You still need to <a style="display: inline;" href="{{ url_for('djudgement.adjudicate', invitation_pk=current_user.sotd_to_invite[sotd_association.sotd.pk]) }}">addjudicate this SOTD.</a></p>
    {% endif %}
    {% if sotd_association.sotd in current_user.sotds_addjudicated %}
      <p> You <a style="display: inline;" href="{{ url_for('djudgement.edit', djudgement_pk=current_user.sotd_to_djudgement[sotd_association.sotd.pk]) }}"> have addjudicated </a>this SOTD.</p>
    {% endif %}
  {% endif %}
  {% if current_user == sotd_association.sotd.author %}
    <p> Your SOTD has
      {% if not  sotd_association.djudgement %}
        not yet
      {% endif %}
      been djudged for {{ format_challenge(sotd_association.challenge) }}.
    </p>
  {% endif %}
  {% for inv in sotd_association.sotd.djudgement_invitations %}
    {% if current_user in inv.challenge.djudges or current_user in inv.challenge.owners %}
      <p>
        {% if inv.djudgement %}
          This SOTD was djudged by {{ format_user(inv.djudge) }} for {{ format_challenge(inv.challenge) }}.
          {% if current_user == inv.sotd_association.djudge %}
            <a style="display: inline;" href="{{ url_for('djudgement.adjudicate',invitation_pk = inv.pk) }}"> Edit djudgement </a>
          {% endif %}
        {% else %}
          This SOTD is on {{ format_user(inv.djudge) }}'s docket for {{ format_challenge(inv.challenge) }}
        {% endif %}
        {% if current_user == inv.sotd_association.djudge and inv.challenge.has_meta_data_check %}
          <p><a style="display: inline;" href="{{ url_for('meta_data.validate', sotd_association_pk=inv.sotd_association.pk) }}"> Edit meta data </a></p>
        {% endif %}
      </p>
    {% endif %}
  {% endfor %}
  {% if show_notes %}
    {% for note in sotd_association.notes %}
      {{ format_note(note, True) }}
    {% endfor %}
  {% endif %}
{% endmacro%}


{% macro format_post(post, challenge) %}
  <a style="display: inline;" href="{{ url_for('post.view', post_pk=post.pk, challenge_pk=challenge.pk) }}">{{ post.title }}</a>
{% endmacro%}

{% macro format_sotd_light(sotd) %}{{ format_user(sotd.author) }} <a style="display: inline;" href="{{ url_for('sotd.view', pk=sotd.pk) }}">posted</a>&nbsp;on {{ sotd.pst_datetime }} (Pacific Standard Time). <a href="https://reddit.com{{ sotd.permalink }}" target="_blank">Reddit Comment</a>    <div style="padding: 10px; border: 2px solid black;">{{ sotd['markdown_text']|safe }} </div>
  {% if sotd.challenges %}
    This SOTD is part of the challenge{% if sotd.challenges|length > 133 %}s{% endif %}
    <ol>
      {% for challenge in sotd.challenges %}
        <li>{{ format_challenge(challenge) }}</li>
      {% endfor %}
    </ol>
  {% endif %}
{% endmacro%}

{% macro format_post(post, challenge) %}
  <a style="display: inline;" href="{{ url_for('post.view', post_pk=post.pk, challenge_pk=challenge.pk) }}">{{ post.title }}</a>
{% endmacro%}

{% macro format_group(group) %}
  <a style="display: inline;" href="{{ url_for('challenge.group_view', group_pk=group.pk) }}">{{ group.name }}</a>
{% endmacro%}